name: aprende_app
description: AplicaciÃ³n educativa @prende+ para fomentar la lectoescritura con  accesibilidad offline.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Utilidades base
  collection: ^1.17.0
  english_words: ^4.0.0
  provider: ^6.0.5

  # ðŸ”¹ Base de datos local
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.0

  # ðŸ”¹ Interfaz y estilo
  cupertino_icons: ^1.0.2

  # ðŸ”¹ Voz y texto (IA)
  flutter_tts: ^3.8.3
  speech_to_text: ^6.5.0
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 # assets:
   # - assets/audio/
    #- assets/images/
#