name: aprende_app
description: AplicaciÃ³n educativa @prende+ para fomentar la lectoescritura con accesibilidad offline.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  
google_fonts: ^6.3.2

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“ Acceso a almacenamiento (guardar audio + JSON)
  path_provider: ^2.1.4
  path: ^1.9.0

  # ðŸ’¾ Base de datos local para alumnos, progreso, etc.
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2

  # ðŸ§  LÃ³gica y utilidades
  collection: ^1.18.0
  english_words: ^4.0.0
  provider: ^6.1.2

  # ðŸŽ¤ TTS y IA (si sigues usando TTS en otras pantallas)
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  google_mlkit_text_recognition: ^0.15.0

  # ðŸ”¥ Firebase (login, datos del alumno, progreso online)
  firebase_core: ^3.4.0     
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12



  # ðŸŽ¨ UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  lottie: ^3.1.0

  # ðŸŒ LocalizaciÃ³n
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Smiling_owl.json
    - assets/animations/Sun_breathing.json
    # - assets/audio/
    # - assets/images/
