name: aprende_app
description: AplicaciÃ³n educativa @prende+ para fomentar la lectoescritura con accesibilidad offline.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸŒ LocalizaciÃ³n
  flutter_localizations:
    sdk: flutter

  # ðŸŽ¨ UI / Fuentes / Animaciones
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  lottie: ^3.1.0

  # ðŸ“ Archivos
  path_provider: ^2.1.4
  path: ^1.9.0

  # ðŸ”Š Voz
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  google_mlkit_text_recognition: ^0.15.0

  # ðŸ”¥ Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # ðŸ§  LÃ³gica y estado
  provider: ^6.1.2
  collection: ^1.18.0
  english_words: ^4.0.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # âš ï¸ SOLO si usas generadores (AHORA MISMO NO USAS NINGUNO)
  # build_runner solo queda instalado por si lo necesitas en el futuro
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Smiling_owl.json
    - assets/animations/Sun_breathing.json

